create database COLLEGE;
use COLLEGE;

create table STUDENT(
	ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(10),
    DEPT_ID INT,
    ADDRESS VARCHAR(20),
    GENDER VARCHAR(7),
    MARKS FLOAT
    );
    
    
    
SELECT " 1)" AS " ";

INSERT INTO STUDENT VALUES(1,'ASWATHI',20,'SREENILAYAM','FEMALE',40);
INSERT INTO STUDENT VALUES(2,'ANAGHA',20,'RTEWRRTWT','FEMALE',80);
INSERT INTO STUDENT VALUES(3,'APARNA',21,'EWRFEWRW','FEMALE',78);
INSERT INTO STUDENT VALUES(4,'APPU',23,'JKGJFHY','MALE',60);
INSERT INTO STUDENT VALUES(5,'SALIM',24,'SDFWFRET','MALE',78);
INSERT INTO STUDENT VALUES(6,'CHRISTY',21,'JYGTHFREE','MALE',90);

SELECT *
FROM STUDENT;

ALTER TABLE STUDENT
ADD CGPA FLOAT;


UPDATE STUDENT
SET CGPA=(MARKS/100)*10;

SELECT *
FROM STUDENT;




SELECT "2)" AS " ";

SELECT DEPT_ID,COUNT(*) AS "NO OF STUDENTS"
FROM STUDENT
GROUP BY DEPT_ID;



SELECT "3)" AS " ";

SELECT NAME,CGPA
FROM STUDENT
ORDER BY CGPA DESC;



SELECT " 4)" AS " ";

CREATE VIEW MAX_CGPA AS 
SELECT DEPT_ID,MAX(CGPA) AS MAX
FROM STUDENT
GROUP BY DEPT_ID;

SELECT *
FROM MAX_CGPA;

SELECT *
FROM STUDENT;




SELECT "5)" AS " ";

SELECT NAME,CGPA,S.DEPT_ID
FROM MAX_CGPA M,STUDENT S
WHERE S.CGPA=M.MAX AND S.DEPT_ID=M.DEPT_ID;

SELECT NAME,CGPA,DEPT_ID
FROM STUDENT S1
WHERE CGPA = ( SELECT MAX(CGPA)
			FROM STUDENT S2
			 WHERE S2.DEPT_ID=S1.DEPT_ID
            GROUP BY DEPT_ID
           );




SELECT "6)" AS " ";

CREATE VIEW SCORE AS 
SELECT NAME,CGPA
FROM STUDENT;

SELECT *
FROM SCORE;




DROP TABLE STUDENT;
DROP DATABASE COLLEGE;
