CREATE DATABASE FACTORY;
USE FACTORY;

CREATE TABLE DEPARTMENT(
		DEPT_ID INT PRIMARY KEY,
        DEPT_NAME VARCHAR(15),
        CITY VARCHAR(15)
        
        );
        
CREATE TABLE EMPLOYEE(
		ID INT PRIMARY KEY,
        NAME VARCHAR(10),
        DEPT_ID INT,
        DESIGNATION VARCHAR(30),
        SALARY FLOAT,
        AGE INT,
        SEX VARCHAR(8),
        FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID)
        );
        

        
SELECT "1)" AS " ";




INSERT INTO DEPARTMENT VALUES
(20,"WEB DEV","KOTTAYAM"),
(21,"APP DEV","PALA"),
(22,"PUBLICITY","ERNAKULAM");

INSERT INTO EMPLOYEE VALUES
(1,"ASWATHI",20,"BACKEND DEVELOPER",20000,21,"FEMALE"),
(2,"REVATHI",21,"FRONTEND DEVELOPER",30000,26,"FEMALE"),
(3,"VARUN",20,"DATABASE ADMINISTRATOR",10000,21,"MALE"),
(4,"SHAHANA",22,"FRONTEND DEVELOPER",80000,56,"MALE");

SELECT *
FROM EMPLOYEE;

SELECT *
FROM DEPARTMENT;




SELECT "2)" AS " ";

SELECT DISTINCT DESIGNATION
FROM EMPLOYEE;




SELECT "3)" AS " ";

SELECT DEPT_NAME,COUNT(*) AS " NO OF FEMALE EMPLOYEES"
FROM EMPLOYEE NATURAL JOIN DEPARTMENT
WHERE SEX='FEMALE'
GROUP BY DEPT_ID;




SELECT "4)" AS " ";

SELECT NAME,SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC;





SELECT "5)" AS " ";

UPDATE EMPLOYEE
SET SALARY=SALARY+500;

SELECT *
FROM EMPLOYEE;




SELECT "6)" AS " ";

CREATE VIEW LOCATION AS 
SELECT NAME,CITY
FROM EMPLOYEE NATURAL JOIN DEPARTMENT;

SELECT *
FROM LOCATION;


DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;


DROP DATABASE FACTORY;
        